"use client";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Clock3, LogIn, LogOut } from "lucide-react";
import { api } from "@/lib/api";
import { useStore } from "@/lib/store";
import EmptyState from "@/components/EmptyState";
import FlowerLoader from "@/components/FlowerLoader";
import { fmtDate, fmtTime } from "@/lib/format";
import type { FloristAttendance } from "@/lib/types";

export default function FloristAttendancePage() {
  const showToast = useStore((s) => s.showToast); const [rows, setRows] = useState<FloristAttendance[] | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(() => api.attendance({ ordering: "-check_in_at" }).then(setRows).catch((e) => showToast(e instanceof Error ? e.message : "Davomat yuklanmadi")), [showToast]); useEffect(() => { load(); }, [load]);
  const action = async (kind: "in" | "out") => { setBusy(true); try { const pos = await new Promise<GeolocationPosition | null>((resolve) => navigator.geolocation?.getCurrentPosition(resolve, () => resolve(null), { timeout: 4000 }) ?? resolve(null)); const data = pos ? { latitude: pos.coords.latitude, longitude: pos.coords.longitude } : undefined; await (kind === "in" ? api.attendanceCheckIn(data) : api.attendanceCheckOut(data)); showToast(kind === "in" ? "✓ Keldi belgilandi" : "✓ Ketdi belgilandi"); load(); } catch (e) { showToast(e instanceof Error ? e.message : "Davomatni belgilab bo'lmadi"); } finally { setBusy(false); } };
  const today = rows?.find((x) => x.work_date === new Date().toISOString().slice(0, 10)); const active = today?.check_in_at && !today.check_out_at;
  if (!rows) return <FlowerLoader />;
  return <div className="flex flex-col gap-5"><div><p className="text-[12px] font-bold uppercase tracking-[2px]" style={{ color: "var(--primary)" }}>Shaxsiy maydon</p><h1 className="mt-1 text-[24px] font-extrabold">Davomat</h1><p className="mt-1 text-[13px]" style={{ color: "var(--muted)" }}>Keldi-ketdi tarixi va bugungi holat</p></div><section className="glass-lite flex flex-wrap items-center gap-4 p-5"><div className="flex h-12 w-12 items-center justify-center rounded-[15px]" style={{ background: active ? "var(--success-soft)" : "var(--primary-soft)", color: active ? "var(--success-ink)" : "var(--primary)" }}>{active ? <CheckCircle2 size={24} /> : <Clock3 size={24} />}</div><div className="mr-auto"><div className="text-[16px] font-bold">{active ? "Hozir ishda" : today?.check_out_at ? "Bugungi ish yakunlangan" : "Bugun hali belgilanmagan"}</div><div className="mt-1 text-[12.5px]" style={{ color: "var(--muted)" }}>{today?.check_in_at ? `Keldi: ${fmtTime(today.check_in_at)}` : "Webdan joylashuv bilan belgilash mumkin"}</div></div><div className="flex gap-2"><button onClick={() => action("in")} disabled={busy || !!today?.check_in_at} className="flex items-center gap-1.5 rounded-[12px] px-4 py-2.5 text-[13px] font-bold text-white disabled:opacity-40" style={{ background: "var(--primary)" }}><LogIn size={16} /> Keldim</button><button onClick={() => action("out")} disabled={busy || !active} className="flex items-center gap-1.5 rounded-[12px] border px-4 py-2.5 text-[13px] font-bold disabled:opacity-40" style={{ borderColor: "var(--border-strong)", color: "var(--text-2)" }}><LogOut size={16} /> Ketdim</button></div></section>{rows.length === 0 ? <EmptyState title="Davomat tarixi yo'q" /> : <section className="glass-lite p-5"><h2 className="mb-3 font-bold">Davomat tarixi</h2>{rows.map((r) => <div key={r.id} className="flex flex-wrap items-center gap-3 border-t py-3 first:border-t-0" style={{ borderColor: "var(--line2)" }}><span className="w-[105px] text-[13px] font-semibold">{fmtDate(r.work_date ?? r.created_at.slice(0, 10))}</span><span className="rounded-full bg-mint px-2.5 py-1 text-[11.5px] font-bold text-mintink">{r.check_in_at ? `Keldi ${fmtTime(r.check_in_at)}` : "Keldi yo'q"}</span><span className="rounded-full bg-tint px-2.5 py-1 text-[11.5px] font-bold">{r.check_out_at ? `Ketdi ${fmtTime(r.check_out_at)}` : "Hali ishda"}</span></div>)}</section>}</div>;
}
